### ISSUE TITLE
디자인 시스템을  적용한다.

### ISSUE THREAD

**Issue by 4BFC** [Farcade-Team/Farcade-Front#1]
## ✈ Task
- [x] styled-components를 적용한다.
- [x] 디자인 시스템을 적용한다.
- [x] index.jsx에 디자인 시스템을 적용한다.
- [x] svg 이미지를 삽입한다.
