### ISSUE TITLE
footer css 변경 사항 적용

### ISSUE THREAD

**Issue by 4BFC** [Farcade-Team/Farcade-Front#13]
## ✈ Task
- [x] footer css 변경 사항 적용
- [x] hover 컬러 변경
- [x] 이미지 전환시 새탭으로 넘어가게 변경
