### ISSUE TITLE
✈Main 페이지의 styled-components 리팩토링

### ISSUE THREAD

**Issue by 4BFC** [Farcade-Team/Farcade-Front#17]
## ✈ Task
- [ ] Main 페이지의 styled-components 리팩토링
  - [ ] 관련 styled-componets들을 상속관계를 이용해서 관리 할 수 있게 한다.
  - [ ] [🚩 common.styled.tsx](https://github.com/Farcade-Team/Farcade-Front/blob/main/src/View/styled/common/Common.styled.jsx) - 사용된 로직을 검토하고 속성들을 파악한다.
  - [ ] [🚩 styled 디렉토리](https://github.com/Farcade-Team/Farcade-Front/tree/main/src/View/styled) - styled컴포넌트의 네이밍을 다시 검토해본다.
- [x] #18
